export enum Paths {
    MAIN = '/main',
    AUTH = '/auth',
    LOGIN = '',
    REGISTRATION = 'registration',
    CONFIRM_EMAIL = 'confirm-email',
    CHANGE_PASSWORD = 'change-password',
    RESULT = '/result',
    ERROR_LOGIN = 'error-login',
    ERROR_USER_EXIST = 'error-user-exist',
    ERROR = 'error',
    SUCCESS = 'success',
    ERROR_CHECK_EMAIL_NO_EXIST = 'error-check-email-no-exist',
    ERROR_CHECK_EMAIL = 'error-check-email',
    ERROR_CHANGE_PASSWORD = 'error-change-password',
    SUCCESS_CHANGE_PASSWORD = 'success-change-password',
    FEEDBACKS = '/feedbacks',
    CALENDAR = '/calendar',
    PROFILE = '/profile',
    SETTINGS = '/settings',
    TRAINING = '/training',
    ACHIEVEMENTS = '/achievements',
}
